# Generated by Django 6.0 on 2026-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
